export enum ActivityFeedEventType {
  MATCH_CONFIRMED = 'MATCH_CONFIRMED',
  CHALLENGE_CREATED = 'CHALLENGE_CREATED',
  CHALLENGE_ACCEPTED = 'CHALLENGE_ACCEPTED',
  CHALLENGE_DECLINED = 'CHALLENGE_DECLINED',
  RANKING_SNAPSHOT_PUBLISHED = 'RANKING_SNAPSHOT_PUBLISHED',
  RANKING_MOVEMENT = 'RANKING_MOVEMENT',
  SYSTEM = 'SYSTEM',
}

