export enum MatchStatus {
  DRAFT = 'DRAFT',
  COORDINATING = 'COORDINATING',
  SCHEDULED = 'SCHEDULED',
  RESULT_REPORTED = 'RESULT_REPORTED',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  DISPUTED = 'DISPUTED',
  VOIDED = 'VOIDED',
  CANCELLED = 'CANCELLED',
}
