export enum MatchDisputeReasonCode {
  WRONG_SCORE = 'WRONG_SCORE',
  WRONG_PLAYERS = 'WRONG_PLAYERS',
  DUPLICATE_MATCH = 'DUPLICATE_MATCH',
  UNSPORTSMANLIKE = 'UNSPORTSMANLIKE',
  OTHER = 'OTHER',
}
