import { ChallengeScheduleProposalStatus } from '../../../challenges/enums/challenge-schedule-proposal-status.enum';
import { LeagueMode } from '../../../leagues/enums/league-mode.enum';
import { MatchType } from '../../../matches/enums/match-type.enum';
import { DisputeStatus } from '../../../matches/enums/dispute-status.enum';
import { MatchAdminOverrideType } from '../../enums/match-admin-override-type.enum';
import { MatchCoordinationStatus } from '../../enums/match-coordination-status.enum';
import { MatchDisputeReasonCode } from '../../enums/match-dispute-reason-code.enum';
import { MatchOriginType } from '../../enums/match-origin-type.enum';
import { MatchRejectionReasonCode } from '../../enums/match-rejection-reason-code.enum';
import { MatchSource } from '../../enums/match-source.enum';
import { MatchStatus } from '../../enums/match-status.enum';
import { MatchTeam } from '../../enums/match-team.enum';
import { MatchVoidReasonCode } from '../../enums/match-void-reason-code.enum';
import { MatchDispute } from '../../entities/match-dispute.entity';
import { MatchMessage } from '../../entities/match-message.entity';
import { MatchProposal } from '../../entities/match-proposal.entity';
import { Match } from '../../entities/match.entity';
import { mapEntityToMatchResponse } from '../../mappers/match-response.mapper';

describe('mapEntityToMatchResponse', () => {
  it('maps canonical fields, setsJson, rankingImpactJson and optional children', () => {
    const match = {
      id: 'match-1',
      originType: MatchOriginType.CHALLENGE_INTENT,
      source: MatchSource.CHALLENGE,
      leagueId: 'league-1',
      competitionMode: LeagueMode.OPEN,
      matchType: MatchType.COMPETITIVE,
      teamAPlayer1Id: 'user-a1',
      teamAPlayer2Id: 'user-a2',
      teamBPlayer1Id: 'user-b1',
      teamBPlayer2Id: 'user-b2',
      status: MatchStatus.RESULT_REPORTED,
      coordinationStatus: MatchCoordinationStatus.SCHEDULED,
      scheduledAt: new Date('2026-03-10T15:00:00.000Z'),
      playedAt: new Date('2026-03-10T16:45:00.000Z'),
      locationLabel: 'Central Court',
      clubId: 'club-1',
      courtId: 'court-1',
      resultReportedAt: new Date('2026-03-10T17:00:00.000Z'),
      resultReportedByUserId: 'user-a1',
      winnerTeam: MatchTeam.A,
      setsJson: [
        { a: 6, b: 4 },
        { a: 7, b: 5 },
      ],
      confirmedAt: null,
      confirmedByUserId: null,
      rejectedAt: null,
      rejectedByUserId: null,
      rejectionReasonCode: null,
      rejectionMessage: null,
      disputedAt: new Date('2026-03-10T18:00:00.000Z'),
      hasOpenDispute: true,
      voidedAt: null,
      voidedByUserId: null,
      voidReasonCode: null,
      impactRanking: true,
      eloApplied: false,
      standingsApplied: false,
      rankingImpactJson: { eloDelta: { userA1: 14 } },
      adminOverrideType: MatchAdminOverrideType.CONFIRM_RESULT,
      adminOverrideByUserId: 'admin-1',
      adminOverrideAt: new Date('2026-03-10T18:10:00.000Z'),
      adminOverrideReason: 'manual override',
      legacyChallengeId: 'legacy-challenge-1',
      legacyMatchResultId: 'legacy-result-1',
      createdAt: new Date('2026-03-09T10:00:00.000Z'),
      updatedAt: new Date('2026-03-10T18:11:00.000Z'),
      version: 3,
    } as unknown as Match;

    const proposals = [
      {
        id: 'proposal-pending',
        proposedByUserId: 'user-b1',
        scheduledAt: new Date('2026-03-09T20:00:00.000Z'),
        locationLabel: null,
        clubId: null,
        courtId: null,
        note: null,
        status: ChallengeScheduleProposalStatus.PENDING,
        createdAt: new Date('2026-03-08T20:00:00.000Z'),
        updatedAt: new Date('2026-03-08T20:30:00.000Z'),
      },
      {
        id: 'proposal-accepted',
        proposedByUserId: 'user-a2',
        scheduledAt: new Date('2026-03-10T15:00:00.000Z'),
        locationLabel: 'Central Court',
        clubId: 'club-1',
        courtId: 'court-1',
        note: 'accepted slot',
        status: ChallengeScheduleProposalStatus.ACCEPTED,
        createdAt: new Date('2026-03-09T09:00:00.000Z'),
        updatedAt: new Date('2026-03-09T10:00:00.000Z'),
      },
    ] as MatchProposal[];

    const messages = [
      {
        id: 'message-1',
        senderUserId: 'user-b2',
        message: 'Running 10 minutes late',
        createdAt: new Date('2026-03-10T14:55:00.000Z'),
      },
    ] as MatchMessage[];

    const dispute = {
      id: 'dispute-1',
      matchId: 'match-1',
      createdByUserId: 'user-b1',
      reasonCode: MatchDisputeReasonCode.WRONG_SCORE,
      message: 'Second set score is wrong',
      status: DisputeStatus.OPEN,
      resolution: null,
      resolutionMessage: null,
      resolvedByUserId: null,
      resolvedAt: null,
      createdAt: new Date('2026-03-10T18:00:00.000Z'),
      updatedAt: new Date('2026-03-10T18:01:00.000Z'),
    } as MatchDispute;

    expect(
      mapEntityToMatchResponse(match, {
        proposals,
        messages,
        dispute,
      }),
    ).toEqual({
      id: 'match-1',
      originType: MatchOriginType.CHALLENGE_INTENT,
      source: MatchSource.CHALLENGE,
      leagueId: 'league-1',
      competitionMode: LeagueMode.OPEN,
      matchType: MatchType.COMPETITIVE,
      teamAPlayer1Id: 'user-a1',
      teamAPlayer2Id: 'user-a2',
      teamBPlayer1Id: 'user-b1',
      teamBPlayer2Id: 'user-b2',
      status: MatchStatus.RESULT_REPORTED,
      coordinationStatus: MatchCoordinationStatus.SCHEDULED,
      scheduledAt: '2026-03-10T15:00:00.000Z',
      playedAt: '2026-03-10T16:45:00.000Z',
      locationLabel: 'Central Court',
      clubId: 'club-1',
      courtId: 'court-1',
      resultReportedAt: '2026-03-10T17:00:00.000Z',
      resultReportedByUserId: 'user-a1',
      winnerTeam: MatchTeam.A,
      sets: [
        { a: 6, b: 4 },
        { a: 7, b: 5 },
      ],
      confirmedAt: null,
      confirmedByUserId: null,
      rejectedAt: null,
      rejectedByUserId: null,
      rejectionReasonCode: null,
      rejectionMessage: null,
      disputedAt: '2026-03-10T18:00:00.000Z',
      hasOpenDispute: true,
      voidedAt: null,
      voidedByUserId: null,
      voidReasonCode: null,
      impactRanking: true,
      eloApplied: false,
      standingsApplied: false,
      rankingImpact: { eloDelta: { userA1: 14 } },
      adminOverrideType: MatchAdminOverrideType.CONFIRM_RESULT,
      adminOverrideByUserId: 'admin-1',
      adminOverrideAt: '2026-03-10T18:10:00.000Z',
      adminOverrideReason: 'manual override',
      legacyChallengeId: 'legacy-challenge-1',
      legacyMatchResultId: 'legacy-result-1',
      createdAt: '2026-03-09T10:00:00.000Z',
      updatedAt: '2026-03-10T18:11:00.000Z',
      version: 3,
      latestAcceptedProposal: {
        id: 'proposal-accepted',
        proposedByUserId: 'user-a2',
        scheduledAt: '2026-03-10T15:00:00.000Z',
        locationLabel: 'Central Court',
        clubId: 'club-1',
        courtId: 'court-1',
        note: 'accepted slot',
        status: ChallengeScheduleProposalStatus.ACCEPTED,
        createdAt: '2026-03-09T09:00:00.000Z',
        updatedAt: '2026-03-09T10:00:00.000Z',
      },
      openDispute: {
        id: 'dispute-1',
        createdByUserId: 'user-b1',
        reasonCode: MatchDisputeReasonCode.WRONG_SCORE,
        message: 'Second set score is wrong',
        status: DisputeStatus.OPEN,
        resolution: null,
        resolutionMessage: null,
        resolvedByUserId: null,
        resolvedAt: null,
        createdAt: '2026-03-10T18:00:00.000Z',
        updatedAt: '2026-03-10T18:01:00.000Z',
      },
      messages: [
        {
          id: 'message-1',
          senderUserId: 'user-b2',
          message: 'Running 10 minutes late',
          createdAt: '2026-03-10T14:55:00.000Z',
        },
      ],
      proposals: [
        {
          id: 'proposal-pending',
          proposedByUserId: 'user-b1',
          scheduledAt: '2026-03-09T20:00:00.000Z',
          locationLabel: null,
          clubId: null,
          courtId: null,
          note: null,
          status: ChallengeScheduleProposalStatus.PENDING,
          createdAt: '2026-03-08T20:00:00.000Z',
          updatedAt: '2026-03-08T20:30:00.000Z',
        },
        {
          id: 'proposal-accepted',
          proposedByUserId: 'user-a2',
          scheduledAt: '2026-03-10T15:00:00.000Z',
          locationLabel: 'Central Court',
          clubId: 'club-1',
          courtId: 'court-1',
          note: 'accepted slot',
          status: ChallengeScheduleProposalStatus.ACCEPTED,
          createdAt: '2026-03-09T09:00:00.000Z',
          updatedAt: '2026-03-09T10:00:00.000Z',
        },
      ],
    });
  });

  it('preserves nullability when optional children are not provided', () => {
    const match = {
      id: 'match-2',
      originType: MatchOriginType.DIRECT_ADMIN,
      source: MatchSource.ADMIN,
      leagueId: null,
      competitionMode: LeagueMode.OPEN,
      matchType: MatchType.FRIENDLY,
      teamAPlayer1Id: 'user-1',
      teamAPlayer2Id: 'user-2',
      teamBPlayer1Id: 'user-3',
      teamBPlayer2Id: 'user-4',
      status: MatchStatus.DRAFT,
      coordinationStatus: MatchCoordinationStatus.NONE,
      scheduledAt: null,
      playedAt: null,
      locationLabel: null,
      clubId: null,
      courtId: null,
      resultReportedAt: null,
      resultReportedByUserId: null,
      winnerTeam: null,
      setsJson: null,
      confirmedAt: null,
      confirmedByUserId: null,
      rejectedAt: null,
      rejectedByUserId: null,
      rejectionReasonCode: MatchRejectionReasonCode.OTHER,
      rejectionMessage: null,
      disputedAt: null,
      hasOpenDispute: false,
      voidedAt: null,
      voidedByUserId: null,
      voidReasonCode: MatchVoidReasonCode.OTHER,
      impactRanking: false,
      eloApplied: false,
      standingsApplied: false,
      rankingImpactJson: null,
      adminOverrideType: null,
      adminOverrideByUserId: null,
      adminOverrideAt: null,
      adminOverrideReason: null,
      legacyChallengeId: null,
      legacyMatchResultId: null,
      createdAt: new Date('2026-03-09T00:00:00.000Z'),
      updatedAt: new Date('2026-03-09T00:00:00.000Z'),
      version: 1,
    } as unknown as Match;

    expect(mapEntityToMatchResponse(match)).toEqual({
      id: 'match-2',
      originType: MatchOriginType.DIRECT_ADMIN,
      source: MatchSource.ADMIN,
      leagueId: null,
      competitionMode: LeagueMode.OPEN,
      matchType: MatchType.FRIENDLY,
      teamAPlayer1Id: 'user-1',
      teamAPlayer2Id: 'user-2',
      teamBPlayer1Id: 'user-3',
      teamBPlayer2Id: 'user-4',
      status: MatchStatus.DRAFT,
      coordinationStatus: MatchCoordinationStatus.NONE,
      scheduledAt: null,
      playedAt: null,
      locationLabel: null,
      clubId: null,
      courtId: null,
      resultReportedAt: null,
      resultReportedByUserId: null,
      winnerTeam: null,
      sets: null,
      confirmedAt: null,
      confirmedByUserId: null,
      rejectedAt: null,
      rejectedByUserId: null,
      rejectionReasonCode: MatchRejectionReasonCode.OTHER,
      rejectionMessage: null,
      disputedAt: null,
      hasOpenDispute: false,
      voidedAt: null,
      voidedByUserId: null,
      voidReasonCode: MatchVoidReasonCode.OTHER,
      impactRanking: false,
      eloApplied: false,
      standingsApplied: false,
      rankingImpact: null,
      adminOverrideType: null,
      adminOverrideByUserId: null,
      adminOverrideAt: null,
      adminOverrideReason: null,
      legacyChallengeId: null,
      legacyMatchResultId: null,
      createdAt: '2026-03-09T00:00:00.000Z',
      updatedAt: '2026-03-09T00:00:00.000Z',
      version: 1,
    });
  });
});
