export enum PlayerStrength {
  SMASH = 'SMASH',
  BANDEJA = 'BANDEJA',
  VIBORA = 'VIBORA',
  VOLEA = 'VOLEA',
  GLOBO = 'GLOBO',
  DEFENSA = 'DEFENSA',
  RESILIENCIA = 'RESILIENCIA',
  TACTICA = 'TACTICA',
  COMUNICACION = 'COMUNICACION',
  VELOCIDAD = 'VELOCIDAD',
  PRECISION = 'PRECISION',
}
