export enum PaymentIntentStatus {
  PENDING = 'PENDING',
  REQUIRES_ACTION = 'REQUIRES_ACTION',
  APPROVED = 'APPROVED',
  FAILED = 'FAILED',
  SUCCEEDED = 'SUCCEEDED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
